# A dockerfile which builds the whole Python code (given it contains a lot of shared
# files), and containers based on this are assumed to run different parts of it.
# See docker-compose files around for more details.
FROM python:3.6

# don't create __pycache__ files
ENV PYTHONDONTWRITEBYTECODE=1

# at first we copy requirements
COPY ./requirements /src/requirements
# then we run install if nothing changed in requirements we'll use cache
RUN pip install -r /src/requirements/test.txt
# then we copy everything else
COPY . /src
# if you want to force update it use docker or docker-compose CLI options
WORKDIR /src
